### ISSUE TITLE
Index Document does not have any index fields. Skip Indexing

### ISSUE THREAD

**Issue by droth86** [dachcom-digital/pimcore-dynamic-search-data-provider-crawler#16]
Hey there,

i'm trying to get our search functionality to work with dynamic-search, lucene and webcrawler.

But i always get the Error "Index Document "document_de_XXXX" does not have any index fields. Skip Indexing...". 

It's clear that the solution should be, to define index fields, but how? I cannot find any documentation on this. Could you help me please with a little example?

Best regards
Dominik

**Comment by KatrinAckermannEk** [comment]
I think, what you are looking for is this example of how to implement an IndexDefinition: https://github.com/dachcom-digital/pimcore-dynamic-search/blob/master/docs/0_ExampleSetup.md#definition

**Comment by solverat** [comment]
Like @KatrinAckermannEk already pointed out, you have to define a definition for your documents / objects first.

Btw I would suggest using the trinity index bundle instead of the webcrawler index bundle.
