### ISSUE TITLE
Wrong call to get resource in HtmlTagExtractor 

### ISSUE THREAD

**Issue by Brainshaker95** [dachcom-digital/pimcore-dynamic-search-data-provider-crawler#4]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

I am pretty sure I found a bug inside of `DsWebCrawlerBundle\Resource\FieldTransformer\Html\HtmlTagExtractor`

As far as I understand the lines 47 - 52 are wrong and need to be changed:

```php
        if (!$resourceContainer->hasAttribute('resource')) {
            return null;
        }

        /** @var SpiderResource $resource */
        $resource = $resourceContainer->getAttribute('resource');
```

to:

```php
        if (!$resourceContainer->hasResource()) {
            return null;
        }

        /** @var SpiderResource $resource */
        $resource = $resourceContainer->getResource();
```

**Comment by solverat** [comment]
thanks!
