### ISSUE TITLE
Wrong type for method

### ISSUE THREAD

**Issue by simonkey** [dachcom-digital/pimcore-dynamic-search-data-provider-crawler#7]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

There is wrong type in the `openFile(string $file, int $mode): mixed` for `$mode` in the class `FilterPersistor`. The mode is always a string and not an int. This triggers an error depending on the error reporting settings.

**Comment by solverat** [comment]
fixed in #12, available in [v2.0.2](https://github.com/dachcom-digital/pimcore-dynamic-search-data-provider-crawler/releases/tag/v2.0.2). Thanks @simonkey!
