### ISSUE TITLE
XPathExpressionDiscoverer selector not working

### ISSUE THREAD

**Issue by simonkey** [dachcom-digital/pimcore-dynamic-search-data-provider-crawler#8]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

In line [196](https://github.com/dachcom-digital/pimcore-dynamic-search-data-provider-crawler/blob/master/src/DsWebCrawlerBundle/Service/CrawlerService.php#L196) of the CrawlerService the selector seems not to work. The problem seems to be the restriction (`Please end your selector with '/a'...`) in the constructur of the XPathExpressionDiscoverer. This issue stops the crawling of the page.

Simplest solution would be an overridden XPathExpressionDiscoverer-Class with removed restriction. That will allow to use the old selector (`//link[@hreflang]|//a[not(@rel='nofollow')]`).

**Comment by dominikschnieper** [comment]
I had the same Problem, it seems there is a missing "|" in the selector. I think it should be like this: //link[@hreflang]|//a[not(@rel='nofollow')]**|**/a

**Comment by solverat** [comment]
fixed in #12, available in [v2.0.2](https://github.com/dachcom-digital/pimcore-dynamic-search-data-provider-crawler/releases/tag/v2.0.2). Thanks @simonkey!
