### ISSUE TITLE
Empty valid links option results in no crawling

### ISSUE THREAD

**Issue by simonkey** [dachcom-digital/pimcore-dynamic-search-data-provider-crawler#9]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? | no
| RFC?             | no

If all links should be valid it's not possible to use an empty array or null for the valid links option. The problem seems to be the check if the `valid_links`-option exists - which will be always true in [the if-condition](https://github.com/dachcom-digital/pimcore-dynamic-search-data-provider-crawler/blob/master/src/DsWebCrawlerBundle/Service/CrawlerService.php#L214). An additional check if the option is empty would solve the problem.

**Comment by solverat** [comment]
fixed in #12, available in [v2.0.2](https://github.com/dachcom-digital/pimcore-dynamic-search-data-provider-crawler/releases/tag/v2.0.2). Thanks @simonkey!
